### PR TITLE
feat : Check config hash and ProgramInfoChanged event

### PR DESCRIPTION
**Pull request by thomas192**
- [x] issue #5 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/piltover/blob/main/Contributing.md)
- [ ] code change includes tests
- [ ] breaking change

Hello first PR ever here, not sure if I needed to make a test (similar PRs haven't seemed to do it).
I implemented the ProgramInfoChanged event also related to issue #5 and discussed in PR #13

### CODE REVIEW

**Comment by b-j-roberts** [comment]
Hey, welcome! If you can rebase / resolve conflicts ( I merged the other ProgramInfo PR ), then add the config hash functionality ( set, get, events, ... ) from the Solidity side that would be a good next step.

I think we also want to have a config hash check in `updateState` like here https://github.com/starkware-libs/cairo-lang/blob/ab6d079f0265f903630aac9287e93d9e7cfb6fcf/src/starkware/starknet/solidity/Starknet.sol#L209 as part of this issue.

**Review by b-j-roberts — COMMENTED** [review]
Hey, welcome! If you can rebase / resolve conflicts ( I merged the other ProgramInfo PR ), then add the config hash functionality ( set, get, events, ... ) from the Solidity side that would be a good next step.

I think we also want to have a config hash check in updateState like here https://github.com/starkware-libs/cairo-lang/blob/ab6d079f0265f903630aac9287e93d9e7cfb6fcf/src/starkware/starknet/solidity/Starknet.sol#L209 as part of this issue.

**Comment by thomas192** [comment]
Hey, I resolved conflicts. 

To make sure I understand your request, a getter and setter for the config hash specifically is needed in addition to the `get_program_info(`) and `set_program_info()` methods of the config component ?

When it comes to the config hash check i think the following snippet from the appchain `update_state()` method does the trick:
```
            let (_, current_config_hash): (felt252, felt252) = self.config.program_info.read();
            assert(
                program_output_struct.config_hash == current_config_hash,
                errors::SNOS_INVALID_CONFIG_HASH
            );
```
Let me know :)

**Comment by b-j-roberts** [comment]
> To make sure I understand your request, a getter and setter for the config hash specifically is needed in addition to the `get_program_info(`) and `set_program_info()` methods of the config component ?

Maybe just the program_info is fine for now, so no worries.

> When it comes to the config hash check i think the following snippet from the appchain `update_state()` method does the trick:
> 
> ```
>             let (_, current_config_hash): (felt252, felt252) = self.config.program_info.read();
>             assert(
>                 program_output_struct.config_hash == current_config_hash,
>                 errors::SNOS_INVALID_CONFIG_HASH
>             );
> ```

👍

**Review by b-j-roberts — APPROVED** [review]

**Pull request merged**
