### PR TITLE
add snforge to dev-dependency

### PR DESCRIPTION
**Pull request by byteZorvin**
- [x ] issue # Cannot add piltover as dependency due to conflicting dependency of sn_forge

One could not add piltover as a dependency due to conflicting dependency of sn_forge, if they are on a later version.
This can be solved by adding sn_forge as a dev-dependency and not dependency

### CODE REVIEW

**Review by glihm — CHANGES_REQUESTED** [review]
Good catch on that, could you ensure that the new OZ version is not breaking everything and new visibility is correctly handled. 👍 Thanks you!

**Comment by byteZorvin** [comment]
Sure, let me get back on this

**Comment by byteZorvin** [comment]
- Have updated to fix the testcases. 
- Had to update the starknet foundry version, as it was incompatible due to compilation from Sierra to Casm failing

**Review by glihm — APPROVED** [review]
Thank you a lot @byteZorvin for the initial push on the version. 🚀

**Pull request merged**
